apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: users_reactions
  namespace: default

spec:

   replicas: 1
   image: postgres:14.1

   database:
      size: 200Mi

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword
