apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: users-reactions
  namespace: default

spec:

   replicas: 1  # we won't read from db very often, so 1 replica should be enough
   image: postgres:14.1

   database:
      size: 200Mi

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-secret
              key: replicationUserPassword
