apiVersion: v1
kind: Service
metadata:
  name: reaction-writer
spec:
  selector:
    app: reaction-writer
  ports:
  - protocol: "TCP"
    port: 8001
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reaction-writer
spec:
  selector:
    matchLabels:
      app: reaction-writer
  replicas: 2
  template:
    metadata:
      labels:
        app: reaction-writer
    spec:
      containers:
      - name: reaction-writer
        image: reaction-writer:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8000
